### ISSUE TITLE
Add instructions for setting up the project for development

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit-lib#103]
Should we add instructions for using `pip` and `python setup.py develop` for working with this lib?

**Comment by Lawouach** [comment]
Good call.

In the past, we used to use `python setupy.py develop`  but it's more common to do `pip install -e .`  these days.

**Comment by russmiles** [comment]
Will change this issue to add those instructions in. What's the difference between `pip install -e` over `python setup.py develop` @Lawouach ? Just curious.

**Comment by Lawouach** [comment]
To be fait, I don't know the exact details. But it's the general trend in the Python ecosystem to do without setup.py altogether in the future and go with a declarative file only (setup.cfg for instance which pip knows how to interpret).
