### ISSUE TITLE
Add a tolerance that takes a distribution

### ISSUE THREAD

**Issue by Lawouach** [chaostoolkit/chaostoolkit-lib#106]
It has been asked if we could check something like "90% of 200 and 10% of 201" on a tolerance probe.

This is not yet possible but worth exploring.

**Comment by mkaszub** [comment]
Is "tolerance" of type probe not a generic "tolerance" that anybody can implement on your own if you need some specific use cases? 
This sound like a specific use case for me. Of course if it is highly demanded such thing could be added. We would have to figure out how to make it generic as a "tolerance" of type probe can get any type of input.
