### ISSUE TITLE
Setuptools should not be in requirements.txt

### ISSUE THREAD

**Issue by arpiagar** [chaostoolkit/chaostoolkit-lib#107]
Please refer to : https://github.com/madzak/python-json-logger/issues/58

We are using the chaostoolkit-lib , it builds and install fine on our machines , howerver when I try to run chaos, it tries to check for setuptools version > 40.6.2 while running which it should not.
setuptools should not be a part of requirements.txt

 File "xxx/3.6/bin/chaos", line 6, in <module>
    from pkg_resources import load_entry_point
  File "xxx/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3089, in <module>
    @_call_aside
  File "xxx/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3073, in _call_aside
    f(*args, **kwargs)
  File "xxx/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3102, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "xxx/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 566, in _build_master
    ws = cls()
  File "xxx/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 590, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "xxx/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'setuptools>=40.6.2' distribution was not found and is required by chaostoolkit-lib

**Comment by Lawouach** [comment]
Hi,

Thanks for the heads up. To be fair, I included *because* it breaks in so many ways when it's not specified. Older versions of setuptools seemed to have different API and if you run against a system-wide setuptools, it's even worse at times.

I don't mind removing it but  if it's breaking something, it's quite the proof things changed.

Could you let us know:

* the system on which you installed
* are you in a venv? system-wide?
* how do did you install it? with pip, poetry, pipenv? 

Thanks,

**Comment by arpiagar** [comment]
Hi ,

- Installed into on a Centos box.

- No, not in a venv . It tries to find the setuptools installed with our python3.6

- we have our own custom packaging which includes setuptools 39.something 

- Also if I try to install via pip , it complains chaostoolkit-lib 1.1.0 has requirement setuptools>=40.6.2, but you'll have setuptools 39.0.1 which is incompatible.

- Not sure why setuptools should be checked while running xxx/3.6/bin/chaos. Failing at build time makes sense but not while running. Thoughts?

**Comment by Lawouach** [comment]
Fair enough. I must admit I have a hard time remembering why I forced it. Let's try to remove it. Do you man creating a PR for this please?

**Comment by arpiagar** [comment]
PR: https://github.com/chaostoolkit/chaostoolkit-lib/pull/108

**Comment by Lawouach** [comment]
This has been merged.

Thanks a lot! :)
