### ISSUE TITLE
Installing the chaostoolkit-lib package only will fail

### ISSUE THREAD

**Issue by Devatoria** [chaostoolkit/chaostoolkit-lib#126]
The `setup.py` file imports `__version__` from the `__init__.py` file: https://github.com/chaostoolkit/chaostoolkit-lib/blob/master/setup.py#L10

However, the `__init__.py` file imports the `logzero` package: https://github.com/chaostoolkit/chaostoolkit-lib/blob/master/chaoslib/__init__.py#L14

It means that if you try to install the `chaostoolkit-lib` package directly with pip, it'll fail even if the `logzero` package is in the `requirements.txt` file because the setup script will be called first. It actually works with the `chaostoolkit` project because it installs the `logzero` package itself before installing the `chaostoolkit-lib` one.

A solution would be to read the version directly from the file without importing it as done in other projects like: https://github.com/chaostoolkit/chaostoolkit-kubernetes/blob/master/setup.py#L10

**Comment by dmartin35** [comment]
This has been fixed with that commit: https://github.com/chaostoolkit/chaostoolkit-lib/commit/6fe7f639f8ca6971f906f9593bf28f4cadf1029a
The issue can be closed.

**Comment by Lawouach** [comment]
True indeed.
