### ISSUE TITLE
HTTP Probe with POST method not allowing UTF-8 

### ISSUE THREAD

**Issue by rkjakeer** [chaostoolkit/chaostoolkit-lib#144]
I tried to use HTTP probe with `POST` metod in `steady_state` for checking my database. But the probe is failing with below error. I can only test with basic "latin-1" encoded text.

```
File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1274, in _send_request
    body = _encode(body, 'body')
  File "/usr/local/lib/python3.7/http/client.py", line 160, in _encode
    (name.title(), data[err.start:err.end], name)) from None
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 102-131: Body ('⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠛⠋⠉⡉⣉⡛⣛) is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```

**Comment by Lawouach** [comment]
Hello,

Thanks for the report. We had in the past issue with encoding/decoding of process output but never with HTTP requests. I will have to look into it.

Would you have some data I could write tests against? What is the encoding of the data you're sending?

**Comment by rkjakeer** [comment]
Hi Sylvain, 

`2H₂ + O₂` is the sample data. I actually tested with Braille characters. 
My Webserver supports the braille characters too. 

Some background:  The default encoding for HTTP POST python request is ISO-8859-1 aka Latin-1. 
chaoslib/provider/http.py is sending the payload(as data=arguments) directly to webserver without checking what text it is. I want as a user I should have the flexibility of letting chaostool know the encoding standard for the text I am using.
```
r = s.request(
                    method, url, data=arguments, headers=headers,
                    timeout=timeout, verify=verify_tls)
```

**Comment by Lawouach** [comment]
Thanks. That's helpful. You are right, we could add an `encoding` argument that you pass to the activity as other args. Would that help? I'm not sure I should define a global encoding but maybe that could also be useful?

**Comment by rkjakeer** [comment]
I don't know whether having global encoding will be beneficient. But at HTTP Probe level encoding argument will help a lot.
