### ISSUE TITLE
Separate rollback from action

### ISSUE THREAD

**Issue by hyder** [chaostoolkit/chaostoolkit-lib#157]
Hi,

Is it possible to distinguish rollbacks from actions? Currently, when I'm choosing actions, the list of rollback actions are displayed. Likewise for when choosing rollbacks, the list of actions is displayed.

Many thanks

**Comment by russmiles** [comment]
Hi @hyder,

Is this question related to using `chaos init`? If it is then this is interesting as currently actions do not imply they are for rollbacks or the method (or for the steady-state hypothesis for that matter, although that block usually only contains probes).

**Comment by hyder** [comment]
Hi,

Yes. This is when using chaos init. Sorry I should have been clearer in my question.

So, when selection an experimental method, because currently there's no way to distinguish between an experimental method or a rollback, all actions, including rollbacks, are displayed at the time of choosing the method. Likewise, when selecting a rollback, the list of experimental methods are also displayed.

It would be great if we can distinguish between the 2.

**Comment by russmiles** [comment]
It is a very interesting requirements, and I can certainly see it being useful. The challenge at the moment is that the chaos toolkit does not have any way of identifying actions as being useful for `method` or `rollbacks` specifically. Technically, any action _could_ be useful in either case, which is why you see all actions for both. Some actions are naturally better-suited as rollbacks though, but at the moment the extensions (where actions are implemented, such as the Kubernetes extension here: ) do not imply that an action could be best used in the `method` or the `rollbacks`. This type of hint _could_ be made, without breaking the current API, but it would have to be carefully thought through to make sure that there was a way of seeing the "recommended" rollback actions, as well as the full list just in case an action that was deemed more _likely_ to be used in a `method` was able to be applied as a rollback action if needed?

**Comment by hyder** [comment]
Understood. Just checking my understanding is correct and I have not made a coding mistake for the extension I'm experimenting with (still learning).

Being able to distinguish between methods and rollbacks can greatly help improve the user experience, particularly for extensions with a large number of modules. It would be nice also at the time of selecting probes/methods/rollbacks, one is able to choose from a list of modules first before picking the actual probes/methods/rollbacks.

e.g. in the kubernetes extension, there are currently the following modules: node, pod, service, statefulset.

Instead of returning the full list of probes first, it would be nice if we can select one of the above module, say pod. This then filters the list of probes available for pods only e.g. read_pod_logs, pods_in_phase, pods_in_conditions etc. Likewise, when selecting methods/rollbacks. 

Extending this idea a bit further, when defining an experiment, select the module > select available probe from module > select available action from module > select available roll_back from module.

Essentially, I'm suggesting a sort of navigation capability when creating the experiment.

Many thanks again for your detailed explanations.

**Comment by russmiles** [comment]
Thank you for your well-thought-out ideas! @Lawouach, does this sound like a good candidate to enter the process of discussion with the broader community, as it would perhaps represent something of an adjustment of meaning of the modules/functions that an extension could provide?

**Comment by Lawouach** [comment]
Hello,

I can certainly see the need considering that `chaos init` is trivially way too basic and has a rather limited UX. So, we could improve there first already.

However, I am not clear how an extension could signal an action is meant for a method or a rollback to be fair. It's really depending on your experiment. It certainly sounds logical to consider one terminates a thing and then start it again. But, one might argue, as Chaos Engineering grows, more exotic scenarios might come to the fore.

That's the crux of the issue, `chaos init`  simply draws its list from the extensions but extension authors cannot decide for you if it's rollback material or method material.

Maybe, it comes to a bigger need of a meta registry (as a public catalog) of known actions that we could then tag as this or that?

**Comment by hyder** [comment]
Hi,

In https://github.com/chaostoolkit/chaostoolkit-lib/blob/master/chaoslib/types.py, an activity is currently either a probe or an action. So, perhaps a 3rd type (rollback) can be added?

Then in https://github.com/chaostoolkit/chaostoolkit-lib/blob/master/chaoslib/discovery/discover.py, a corresponding function (discover_rollback) can similarly be added.

Extension developers can then decide whether a particular activity is a probe, an action or a rollback and they can add their rollbacks in a rollbacks.py in the module. The rollbacks can then be loaded into the activities list just like probes and actions:

``
    activities.extend(discover_probes("chaos<extension>.<module>.probes"))
    activities.extend(discover_actions("chaos<extension>.<module>.actions"))
    activities.extend(discover_rollbacks("chaos<extension>.<module>.rollbacks"))
``

What do you think? Is this reasonable?
