### ISSUE TITLE
Validate should reject unrecognised top level elements, recommending that they consider being moved to the extensions block

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit-lib#158]
I've found that I can add any custom top level element to an experiment and validation seems to ignore it. Should validation catch this misuse of the contents of an experiment? Perhaps pointing me to add a custom, `extensions` block instead?

**Comment by Lawouach** [comment]
I'm not sure there was anything in the specification for that. I think that was done on purpose. Maybe we should clarify the specification for this. But be aware also that becoming stricter now may have some undesired side effects for folks who have embedded their own elements at the root level.

**Comment by russmiles** [comment]
It sounds like something to put to the community first? As a RFC kinda thing?
