### ISSUE TITLE
Default values can't be empty strings

### ISSUE THREAD

**Issue by idanto** [chaostoolkit/chaostoolkit-lib#165]
In this [line](https://github.com/chaostoolkit/chaostoolkit-lib/blob/1.8.1/chaoslib/configuration.py#L56) you check if the value exists not by using `is None` instead you use `not` which throw and error in case of empty string `""`.

In our case, we use `chaostoolkit-aws` and in one case we would like to use a profile but in our hosts, we would like to use the instance attached IAM role, therefore, we would like to pass an empty string as default so `boto3` will fallback to the attached role.

If you solve that it can help to prevent a possible issue with numeric variables cause `not` will be `false` for 0 value as well.

Another option to solve that is to add another attribute called `optional` with a boolean value and add it to the validation check.

**Comment by Lawouach** [comment]
Oooh very good and subtle catch actually!

I'll fix it yes. Probably a release by tomorrow now.
