### ISSUE TITLE
How to programmatically get experiment start time?

### ISSUE THREAD

**Issue by dimzak** [chaostoolkit/chaostoolkit-lib#166]
In one of our scenarios we are using a probe that checks if our system generated any errors during the duration of the experiment. 
To do that we currently hard-code a `timestamp` field that is used to check for errors from a specific time onward.

Ideally we would like to use `journal.start` instead of above hack but looks like journal is not available until the end of the experiment.

Is there a way to fetch the start time of ongoing experiment using python?

**Comment by Lawouach** [comment]
Hey @dimzak, right now, the best solution IMO is to create a control that injects said timestamp to the right probe's arguments mapping.

**Comment by dimzak** [comment]
Hi @Lawouach yes will try that, alternatively was thinking to try to have `timestamp` persisted somehow e.g. first probe runs, stores current timestamp so the next one picks that timestamp up.

Is exposure of experiment start time to probes maybe a feature for later ? 
if not, this issue should be closed :slightly_smiling_face:

**Comment by Lawouach** [comment]
Hey @dimzak, unfortunately, the CTK does not expose its internal state to activities like that to avoid some shenanigans with state manamenent :)

For now, the best and only answer I can provide is through controls which have that liberty.

I'll be closing this one if that's okay indeed.
