### ISSUE TITLE
Drop python 3.5 support - EOL - 

### ISSUE THREAD

**Issue by dmartin35** [chaostoolkit/chaostoolkit-lib#187]
Python 3.5 will reach its "end of life" at the end of September 2020.

We shall consider upgrading minimal version to python 3.6.

**Comment by dmartin35** [comment]
FYI pip 21.0 will drop support for Python 3.5 in January 2021

**Comment by Lawouach** [comment]
I'm all for it.

I wonder if we shouldn't consider going straight to Python 3.7 as a baseline?

**Comment by Lawouach** [comment]
done and released lats version supporting Python 3.5 as 1.18.3
