### ISSUE TITLE
Rallback is not executed if one of methods is failing

### ISSUE THREAD

**Issue by AlexShemeshWix** [chaostoolkit/chaostoolkit-lib#189]
Hi
Ive upgraded recently to chaostoolkit 1.7.0. After that my chaos experiments started to behave differently.
If one of the actions failed, or steady state in the end of experiment was failing, rollback would not be executed.
as temporary solution ive added --rollback-strategy=always flag. It works now but it gives annoying warning.
I think this is not logical, rollbacks should always be executed . In rollbacks i remove labels and tags from my instances. If i dont do it other people start to ask questions if i really need to use 20 instances in aws for chaos experiments and if they can work with instances with chaos tags. 
Please explain the logic behind this new functionality.

**Comment by Lawouach** [comment]
Hello @AlexShemeshWix,

I tried with CTK 1.5.0/chaoslib 1.11.0 and I get the following:

* a deviating experiment doesn't play rollbacks (so if the ssh fails after the method)
* a failing action (ActivityFailed) in the method doesn't prevent rollbacks to be executed

**Comment by IoannisGrafis** [comment]
Hello,
I have the same issue as @AlexShemeshWix.

Based on the Execution Flow Diagram https://docs.chaostoolkit.org/reference/tutorials/run-flow/, if the second steady-state hypothesis deviates, the status should be `completed`.
But, I see in the code, that the status is set to `failed` if the second steady-state hypothesis deviates. Function `run_deviation_validation_hypothesis ` https://github.com/chaostoolkit/chaostoolkit-lib/blob/73edaa7acc7b337711cd1e8b843506a58b268e38/chaoslib/run.py#L502-L505
