### ISSUE TITLE
It will be great if we will have the ability to put a decorator that wraps the events functions in the control

### ISSUE THREAD

**Issue by roeiK-wix** [chaostoolkit/chaostoolkit-lib#197]
My team and I tried to put a decorator above one or more of the control events, and we figure that this function is never called.
 - Can you explain why?
 - Can you make it happened?
 
Thanks.

**Comment by Lawouach** [comment]
Hello, 

Could you please show an example of what you mean and tried? I'm not sure I understand.

Cheers,

**Comment by roeiK-wix** [comment]
In this example, we want to wrap the configure_control event and inject some modules we created (in this case - MyLog).
When I tried to wrap that event (or any other event in the control) and inject something, the event doesn't happen and doesn't execute.
`
@MyLog(file_name)
def configure_control(
    configuration: Configuration = None,
    secrets: Secrets = None,
    settings: Settings = None,
    experiment: Experiment = None,
    probes: List[Probe] = None,
    **logger: MyLog = None,**
): 
   logger.info("Some info!")
   `
   
   Please tell me if you understand.
   
   Thanks

**Comment by Lawouach** [comment]
I do. It's very interesting that it seems to fail. I'll have to give it a try.
