### ISSUE TITLE
Split probes/actions with property pauses into two activities

### ISSUE THREAD

**Issue by roeiK-wix** [chaostoolkit/chaostoolkit-lib#198]
We encounter an issue with the pause ability.
currently, we have an action that doing something, and afterward, we want to pause for some time.
Also, we want to send a message to slack that this action is executed and also a slack message that the pausing has begun after this action.
(We are using the `before_activity_control` event for that.)

The problem is that we have also a slack message inside that action. 
So, what we are seeing on slack is:
`Action executed..`
`Pausing for 360s`
`Some message inside the action..`

* If we will print the pause in `after_activity_control` it will be too late (After the 360s)
Right now we solve this using a patch, we create an empty probe that does nothing and executed right after this action, and so we added to that probe the pause property.
This is our temporary solution.

Can you help us with that issue, maybe split those functionalities in the controls?

**Comment by Lawouach** [comment]
Hello,

I think, we could add a control that is before the activity is paused? Would that help?

**Comment by roeiK-wix** [comment]
This will do the trick!
Excellent idea. :)

**Comment by Lawouach** [comment]
I'll do my best to add it this week.

**Comment by roeiK-wix** [comment]
> I'll do my best to add it this week.

Thanks!
