### ISSUE TITLE
Secrets should allow for arbitrary levels of nesting

### ISSUE THREAD

**Issue by Tam-Lin** [chaostoolkit/chaostoolkit-lib#209]
**Is your feature request related to a problem? Please describe.**
For the chaos toolkit plugin I'm working into, there are multiple ways of connecting to a device and authenticating.  I'd like to hide that as much as possible in the toolkit, by allowing the extension to figure things out and connect appropriately.  Right now, though, you can't pass in multiple levels of json that get resolved out of the environment or I'm assuming vaults.  For example, 
```

    "zos_console": {
      "M89 S5C": {
        "method": "hmc",
        "hostname": "ioshmc3.pok.stglabs.ibm.com",
        "userid": {
          "type": "env",
          "key": "IOSHMC3_USERID"
        },
        "password": {
          "type": "env",
          "key": "IOSHMC3_PASSWORD"
        }
      }
    }


```

doesn't work, but 

```
    "zos_console": {
      "M89 S5C": {
        "method": "hmc",
        "hostname": "ioshmc3.pok.stglabs.ibm.com",
        "userid": "<userid>",
        "password": "<mypassword>"

      }
    }
```

does work.

**Describe the solution you'd like**

You should be able to include environmental or vault keys at any level of JSON nesting.  The Secrets object is supposed to be able to be an arbitrary JSON object; there's no reason I know of to restrict where keys can be pulled from the environment.

**Describe alternatives you've considered**
I can restructure the plugin, but I'd prefer not to.  And, again, it doesn't make sense to allow arbitrary of nesting of JSON objects, but not to allow variables to be held externally only 2 levels deep.

**Additional context**

**Comment by Lawouach** [comment]
Hey, thanks for the report. This migt be a bug or a limitation to fix indeed.

**Comment by Tam-Lin** [comment]
I'm going to try to fix it; I just need some time to work on it.  Expect a pull request in a few days.
