### ISSUE TITLE
Secrets testing taking advantage of side effect

### ISSUE THREAD

**Issue by Tam-Lin** [chaostoolkit/chaostoolkit-lib#210]
**Is your feature request related to a problem? Please describe.**
I'm trying to understand the project enough to address #209 , and noticed that in the test_secret.py file, in some functions you were specifying at the top     
```
os.environ["KUBE_API_URL"] = "http://1.2.3.4"
```

and in others you weren't, but you're checking in multiple places where you weren't doing the assignment at the top that KUBE_API_URL resolves to "http://1.2.3.4".  Some of the testcases, like test_should_load_inline and test_should_merge_properly are working due to os.environ being a global namespace, and so the declare in test_should_load_environment applying to all the later testcases.  

**Describe the solution you'd like**

I'd prefer not to use a side-effect in testcases.  So I'd prefer to replace the os.environ statements at the beginning of some of the testcases with 
```@patch.dict(os.environ, {"KUBE_API_URL": "http://1.2.3.4"})```

**Describe alternatives you've considered**

Other options would be to put 
```os.environ["KUBE_API_URL"] = "http://1.2.3.4"```
at the beginning of all the testcases, so it's at least clear where that's coming from, or remove it from all but the first.  But both of those are potentially confusing in different ways.

**Comment by ciaranevans** [comment]
Closed by #236
