### ISSUE TITLE
Support for hooks/events

### ISSUE THREAD

**Issue by SudoQ** [chaostoolkit/chaostoolkit-lib#33]
I would be nice to be able to perform actions before and after certain points in an experiment.
Some ideas/examples: 
- Before running an experiment, announce to a slack channel that we are about to run an chaos experiment.
- After finishing the experiment, announce that it has finished.
- Before and after each probe, log the results to some log server on a customised format.
- If we had to run a rollback, send an email to the service owner so they can check that everything looks fine.

**Comment by Lawouach** [comment]
Hey @SudoQ, I implemented a first version of this request.

http://chaostoolkit.org/reference/usage/notification/

For now, I do not track the activities themselves. This will come in a second round. But hopefully, it should show be a good start!

**Comment by Lawouach** [comment]
The reason I didn't implement an event per-activity is because those activities are deeper into the flow and I want to think more thoroughly about it. But I would need those events too so consider this isn't the end of it :)
