### ISSUE TITLE
Can we pass results from one activity to the rest of the experiment?

### ISSUE THREAD

**Issue by Lawouach** [chaostoolkit/chaostoolkit-lib#44]
The tookit does its best to not have a global state and so far, there was never really a need to take the output of an activity and feed it into another activity. But there are cases when this is useful (when an operation returns an ID for instance).

Let's see how we can add this.

**Comment by devin-fisher** [comment]
I think this could be especially useful for rolling back changes made by an activity. 

For example, in a distributed system that has a master. An activity could stop the master. The system responds by electing a new master. In the rollback, you may want to restart the node that was the old master but it may be hard to know what node that was. If the activity that stopped it could communicate what node was stopped it would be trivial to restart it.

**Comment by Lawouach** [comment]
Generally speaking, I see a simple way here. The chaostoolkit feeds automatically the outputs of past experiments. For instance:

```json
{
   "type": "action",
   "name": "create-new-stuff",
   "provider": ....
},
{
   "type": "action",
   "name": "delete-new-stuff",
   "provider": {
        ....
        "arguments": {
             "id": {
                 "source": "create-new-stuff",
                 "type": "jsonpath",
                 "path": "..."
             }
    }
}

```

In this pseudo-code example, we tell chaostoolkit that the second action arguments consists of the value found in the first action's output (and found using the jsonpath query).

This means we could let actions indicate where to find values they need.

wdyt?

**Comment by theodelaune** [comment]
I think it makes sense to use this structure.

 I would like to add also type "string", in case where the past experiment returns just a job ID.

**Comment by Lawouach** [comment]
Yeah, that would make sense and follow other similar structures in the spec.

**Comment by 0rc** [comment]
this would be extremely useful

**Comment by Lawouach** [comment]
Back to this one, by popular demand :)

I think the format I offered earlier is not simple enough. Maybe this instead:

```
{
   "type": "action",
   "name": "create-new-stuff",
   "provider": ....
   "output": "some-id"
},
{
   "type": "action",
   "name": "delete-stuff",
   "provider": {
        "arguments": {
             "id": "${some-id}"
        }
},
```

We could also see if we could support this:
```
{
   "type": "action",
   "name": "create-new-stuff-returning-json",
   "provider": ....
   "output": {
       "id": "some-id",
       "jsonpath": "..."
   }
},
{
   "type": "action",
   "name": "delete-stuff",
   "provider": {
        "arguments": {
             "id": "${some-id}"
        }
},
```

so we could bind the output var to a specific value in the returned output.

I'm wondering if the reference should be directly the id or `${output.some-id}` to clarify the source.

**Comment by Lawouach** [comment]
Yeap, Likely, the chaostoolkit should see the returned data as an opaque payload more than a specific type.

**Comment by venkivijay** [comment]
> Generally speaking, I see a simple way here. The chaostoolkit feeds automatically the outputs of past experiments. For instance:
> 
> ```json
> {
>    "type": "action",
>    "name": "create-new-stuff",
>    "provider": ....
> },
> {
>    "type": "action",
>    "name": "delete-new-stuff",
>    "provider": {
>         ....
>         "arguments": {
>              "id": {
>                  "source": "create-new-stuff",
>                  "type": "jsonpath",
>                  "path": "..."
>              }
>     }
> }
> ```
> 
> In this pseudo-code example, we tell chaostoolkit that the second action arguments consists of the value found in the first action's output (and found using the jsonpath query).
> 
> This means we could let actions indicate where to find values they need.
> 
> wdyt?

Is this feature available?

**Comment by Lawouach** [comment]
Hello, unfortunately not.
