### ISSUE TITLE
chaos returns 0 exit code for a failed experiment 

### ISSUE THREAD

**Issue by devin-fisher** [chaostoolkit/chaostoolkit-lib#45]
I was trying to script chaos to run continuously if the experiment was successful. 

The script was simple:
```
chaos run ./experiments/consensus-recovery.json
while [ $? -eq 0 ]; do
    chaos run ./experiments/consensus-recovery.json
done
```
Eventually, the experiment stopped being successful but continued to run.

**Comment by Lawouach** [comment]
Oh! Very good catch, I didn't think of being a good citizen here!.

**Comment by Lawouach** [comment]
This is an interesting one. We have always considered that, unless the experiment is aborted, we consider the process complete and therefore successful. No matter the status of the experiment itself. We make a distinction between the process of running it and the status of whatever you declared.

However, I do see the need for automation such as the one you mention here so I'm incline to link the process exit code to the status of the experiment itself.
