### ISSUE TITLE
Consider using schema validation

### ISSUE THREAD

**Issue by Lawouach** [chaostoolkit/chaostoolkit-lib#50]
While the current validation does an okay job, it can't handle some important cases in the data that are being passed on.

It might be useful to rely on schema validation https://github.com/keleshev/schema

**Comment by russmiles** [comment]
Nice idea. Do you have examples of what those important cases are @Lawouach ?

**Comment by Lawouach** [comment]
Comes to mind data type validation. Right now, we can't validate that the type of arguments match the arguments of an action (nor its return value).

To be fair, this needs reviewing and not needed for now.

**Comment by Lawouach** [comment]
Let's close this one for now.
