### ISSUE TITLE
when using probe in `method` tolerance is not validated

### ISSUE THREAD

**Issue by 0rc** [chaostoolkit/chaostoolkit-lib#55]
Hi,

I just noticed that it is allowed to use probes inside `method` as opposed to `steady-state-hypothesis` but at the same time tolerance is not validated when doing so.

I find it useful to use probes inside `method`, first example use case I have is when I don't want to run probe both before and after some actions. Instead the probe can be used to validate some conditions in the middle of experiment. For example, I stop a random instance in ASG and if it's not marked unhealthy (or perhaps is not replaced fast) I don't want to continue with the experiment.

Please advice if this behavior is by intention or by accident.

**Comment by 0rc** [comment]
[here](https://github.com/chaostoolkit/chaostoolkit-lib/blob/master/chaoslib/activity.py#L175)
I'd prefer to have something that will fail the experiment when `activity` is `probe` and it is not in defined `tolerance`

Also (just thinking) it can be useful to specify `tolerance` for `action` too to have more control over the experiment

**Comment by russmiles** [comment]
It's an excellent point @0rc . At the moment this is working as intended as probes in an experiment's method are intended to collect additional information during an experiment's execution, and not to provide any early-experiment-aborting logic.

That's not to say that such control is a bad thing, but it's not currently the intention of these probes.

**Comment by russmiles** [comment]
This might be a further refinement/requirement on this issue: https://github.com/chaostoolkit/chaostoolkit/issues/74

**Comment by 0rc** [comment]
Yes I will add this point to https://github.com/chaostoolkit/chaostoolkit/issues/74

And yes, I just double-checked the documentation and it doesn't say `tolerance` is supported when using `probe` in `method`. But still it may be better to mention explicitly it's not supported unless we can add it soon

But what are other opinions, do you guys think it's useful to have `tolerance` supported inside `method`?

**Comment by SaydChada** [comment]
This should be available in some way... What i saw is that most of the chaostoolkit libs (as for exemple k8s) uses probs func as a way to raise **chaoslib.exceptions.ActivityFailed** when it fails. 
For those who are not familar with python, having a way to validate tolerance activity probs in method can be very helpful.

**Comment by maximmold** [comment]
My use case is that I want to kill a node and ensure the node is actually killed before proceeding with the steady state hypothesis which I would initially expect to fail on my one node cluster. Currently, it just drops through to the steady state hypothesis and passes before azure has actually stopped the node which is a false positive.

**Comment by Lawouach** [comment]
I think we are getting more and more ready for this to be an implemented feature considering how many folks need it :)
