### ISSUE TITLE
Provide a way to mak an action as "dangerous"

### ISSUE THREAD

**Issue by Lawouach** [chaostoolkit/chaostoolkit-lib#71]
While Chaos Engineering make degrade the system, we should be careful not to harm too massively. So, having a mechanism to mark an action as "dangerous" could help those use cases.

From the CLI side, this could translate into asking the users before running an experiment?

**Comment by buderre** [comment]
The CLI should anyway have the opportunity (by a "--yes" flag for example) to avoid a prompt for interactive confirmation. (For people that do have automated tasks and know the risks.)
