### ISSUE TITLE
Allow to setup headers when loading experiments over HTTP

### ISSUE THREAD

**Issue by Lawouach** [chaostoolkit/chaostoolkit-lib#79]
Currently loading experiments over HTTP forces the Accept header to static values of:

```
"application/json, application/x-yaml"
```

In some cases, this should be amended by the operator.

**Comment by neil-advani** [comment]
This would definitely be helpful. I did this by hardcoding values and for valid experiments there seemed to be no issues (thats all I tested). Probably a simple change such as adding a "headers" option to the configuration, similarly to how authorization is currently done
