### ISSUE TITLE
Chaos Toolkit model link to doc is broken

### ISSUE THREAD

**Issue by dmartin35** [chaostoolkit/chaostoolkit-lib#83]
In the readme, the __Chaos Toolkit model__ link (http://chaostoolkit.org/overview/concepts/) is broken (404)

by the way, your 404 page contains weird content "Cloud bread lo-fi woke echo park cronut plaid banjo hammock fingerstache ennui gentrify fashion axe poke. ... " is this wanted ?

**Comment by russmiles** [comment]
Thanks for this! You're absolutely right that it is broken, and the 404 page is even more so...

**Comment by russmiles** [comment]
I'm going to create a new issue over at the docs for the 404 page @dmartin35

**Comment by russmiles** [comment]
No issue is needed on the docs as the 404 issue is in fact on a different site (chaostoolkit.org specifically). Fixing that elsewhere.
