### ISSUE TITLE
Enable global controls from the settings

### ISSUE THREAD

**Issue by Lawouach** [chaostoolkit/chaostoolkit-lib#99]
It would be valuable to allow controls to be declared and defined in the settings and applied globally no matter the experiment.

**Comment by dimzak** [comment]
Was really looking forward to this issue so gave it a try with `chaostoolkit==1.1.0`, `chaostoolkit-lib==1.2.0` and `chaostoolkit-opentracing`.

Unfortunately seems that `experiment.configuration` is not loaded at all for controls declared in `settings.yaml` (https://github.com/chaostoolkit/chaostoolkit-lib/blob/master/chaoslib/control/__init__.py#L126). 

Is this the expected behaviour and if it is, is there a possible workaround like adding some  of the `experiment.configuration` props in `settings.xml`?
 
Documentation should mention this imho as `configuration` is also an arg for multiple control methods and now it will be `None`

**Comment by russmiles** [comment]
For secrets, this sounds like somewhat sensible behaviour as registering a global control means selecting the right secrets block could be tricky. For configuration it seems that it should be passed automatically around.

**Comment by Lawouach** [comment]
Hello,

The trick is that the configuration/secrets targets the experiment. The whole point of declaring controls outside of the experiment means the experiment isn't aware of them. For progressing this question, I'd like examples of scenarios where you declare them globally but configure them locally.

Technically speaking global controls are loaded before the experiment and therefore before secrets and configs have been resolved. The idea is that global controls have access to the settings entirely (unlike experiments).

Agreed on better docs.

**Comment by dimzak** [comment]
Sure let's take 2 different scenarios that we currently have:
1. `chaostoolkit-opentracing` requires this piece of configuration per experiment:
```
"configuration": {
  "tracing_provider": "jaeger",
  "tracing_host": "jaeger",
  "tracing_port": 6831
}
```
Is this configuration specific to an experiment? Not really it's not! yet every experiment requires it to run this control. 

2. We have another control, let's name it `generic_control` that requires this piece of configuration per experiment:
```
"configuration": {
  "project": "projectA",
  "region": "us-east-1"
}
```
while this piece of configuration is per experiment, all of our experiments require it so by having `generic_control` in `settings.yaml` reading this block will mean a cleaner experiment for our users

**Comment by Lawouach** [comment]
Thanks. The first example isn't too much of an issue I believe. If i recall well, you can set args on the control itself. Even on the global one. To be verified.

The other one makes more sense indeed. I need to figure out how work around this elegantly.

**Comment by Lawouach** [comment]
Hi @dimzak, I've pushed some code in #116 to support this.

If you feel like trying before it's released, you'll need to update chaostoolkit-lib and chaostoolkit to the latest HEAD of each repo's master branch.

**Comment by dimzak** [comment]
Hi @Lawouach !
Sorry for the late response, finally got time to test latest versions of `chaostoolkit` and `chaostoolkit-lib` (saw that you already merged open prs and released new versions).

Controls work like a charm!
Experiments now do not have a `controls: []` section at all as controls are loaded from `settings.yaml`.

Thank you very much!
